USE [master]
GO

/****** Object:  Database [TP_FINAL_DB]    Script Date: 18/6/2022 15:34:35 ******/
CREATE DATABASE [TP_FINAL_DB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TP_FINAL_DB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\TP_FINAL_DB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'TP_FINAL_DB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\TP_FINAL_DB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TP_FINAL_DB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [TP_FINAL_DB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [TP_FINAL_DB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [TP_FINAL_DB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [TP_FINAL_DB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [TP_FINAL_DB] SET ARITHABORT OFF 
GO

ALTER DATABASE [TP_FINAL_DB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [TP_FINAL_DB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [TP_FINAL_DB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [TP_FINAL_DB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [TP_FINAL_DB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [TP_FINAL_DB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [TP_FINAL_DB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [TP_FINAL_DB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [TP_FINAL_DB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [TP_FINAL_DB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [TP_FINAL_DB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [TP_FINAL_DB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [TP_FINAL_DB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [TP_FINAL_DB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [TP_FINAL_DB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [TP_FINAL_DB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [TP_FINAL_DB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [TP_FINAL_DB] SET RECOVERY FULL 
GO

ALTER DATABASE [TP_FINAL_DB] SET  MULTI_USER 
GO

ALTER DATABASE [TP_FINAL_DB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [TP_FINAL_DB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [TP_FINAL_DB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [TP_FINAL_DB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [TP_FINAL_DB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [TP_FINAL_DB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [TP_FINAL_DB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [TP_FINAL_DB] SET  READ_WRITE 
GO

USE [TP_FINAL_DB]
GO

USE [TP_FINAL_DB]
GO

/****** Object:  Table [dbo].[Productos]    Script Date: 18/6/2022 17:00:54 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Productos](
	[id] [int] NOT NULL,
	[marca] [varchar](50) NOT NULL,
	[tipo] [varchar](50) NOT NULL,
	[precio] [float] NOT NULL,
 CONSTRAINT [PK_Productos] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO



/****** Object:  Table [dbo].[Clientes]    Script Date: 18/6/2022 16:58:18 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Clientes](
	[id] [int] NOT NULL,
	[nombre] [varchar](50) NOT NULL,
	[apellido] [varchar](50) NOT NULL,
 CONSTRAINT [PK_Clientes] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

USE [TP_FINAL_DB]
GO

/****** Object:  Table [dbo].[Mensajes]    Script Date: 18/6/2022 16:58:35 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Mensajes](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[contenido] [varchar](1000) NOT NULL,
	[id_cliente] [int] NOT NULL,
 CONSTRAINT [PK_Mensajes] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Mensajes]  WITH CHECK ADD  CONSTRAINT [FK_Mensajes_Clientes] FOREIGN KEY([id_cliente])
REFERENCES [dbo].[Clientes] ([id])
GO

ALTER TABLE [dbo].[Mensajes] CHECK CONSTRAINT [FK_Mensajes_Clientes]
GO

insert into Productos (id, marca, tipo, precio) values 
(1, 'Samsung', 'Celular', 30000),
(2, 'Gibson', 'Guitarra', 80000),
(3, 'LG', 'Televisor', 45000),
(4, 'Patrick', 'Heladera', 85000),
(5, 'Yamaha', 'Saxo', 120000);



